addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.12.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.9")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.10.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.5.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "3.9.15")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"                       % "2.2.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                      % "2.3.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"           % "0.21.1")
// for Scala.js 1.x.x
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta40")
