package org.emergentorder.onnx

trait ONNXFull
    extends Abs
    with Acos
    with Acosh
    with Add
    with And
    with ArgMax
    with ArgMin
    with ArrayFeatureExtractor
    with Asin
    with Asinh
    with Atan
    with AveragePool
    with BatchNormalization
    with Binarizer
    with BitShift
    with Cast
    with CastMap
    with CategoryMapper
    with Ceil
    with Clip
    with Compress
    with Concat
    with ConcatFromSequence
    with Constant
    with ConstantOfShape
    with Conv
    with ConvInteger
    with ConvTranspose
    with Cos
    with Cosh
    with CumSum
    with DepthToSpace
    with DequantizeLinear
    with Det
    with DictVectorizer
    with Div
    with Dropout
    with DynamicQuantizeLinear
    with Elu
    with Equal
    with Erf
    with Exp
    with Expand
    with EyeLike
    with Flatten
    with Floor
    with GRU
    with Gather
    with GatherElements
    with GatherND
    with Gemm
    with GlobalAveragePool
    with GlobalLpPool
    with GlobalMaxPool
    with Greater
    with HardSigmoid
    with Hardmax
    with Identity
    with If
    with Imputer
    with InstanceNormalization
    with IsInf
    with IsNaN
    with LRN
    with LSTM
    with LabelEncoder
    with LeakyRelu
    with Less
    with LinearClassifier
    with LinearRegressor
    with Log
    with LogSoftmax
    with Loop
    with LpNormalization
    with LpPool
    with MatMul
    with MatMulInteger
    with Max
    with MaxPool
    with MaxRoiPool
    with MaxUnpool
    with Mean
    with MeanVarianceNormalization
    with Min
    with Mod
    with Mul
    with Multinomial
    with Neg
    with NonMaxSuppression
    with NonZero
    with Normalizer
    with Not
    with OneHot
    with OneHotEncoder
    with Or
    with PRelu
    with Pad
    with Pow
    with QLinearConv
    with QLinearMatMul
    with QuantizeLinear
    with RNN
    with RandomNormal
    with RandomNormalLike
    with RandomUniform
    with RandomUniformLike
    with Range
    with Reciprocal
    with ReduceL1
    with ReduceL2
    with ReduceLogSum
    with ReduceLogSumExp
    with ReduceMax
    with ReduceMean
    with ReduceMin
    with ReduceProd
    with ReduceSum
    with ReduceSumSquare
    with Relu
    with Reshape
    with Resize
    with ReverseSequence
    with RoiAlign
    with Round
    with SVMClassifier
    with SVMRegressor
    with Scaler
    with Scan
    with Scatter
    with ScatterElements
    with ScatterND
    with Selu
    with SequenceAt
    with SequenceConstruct
    with SequenceEmpty
    with SequenceErase
    with SequenceInsert
    with SequenceLength
    with Shape
    with Shrink
    with Sigmoid
    with Sign
    with Sin
    with Sinh
    with Size
    with Slice
    with Softmax
    with Softplus
    with Softsign
    with SpaceToDepth
    with Split
    with SplitToSequence
    with Sqrt
    with Squeeze
    with StringNormalizer
    with Sub
    with Sum
    with Tan
    with Tanh
    with TfIdfVectorizer
    with ThresholdedRelu
    with Tile
    with TopK
    with Transpose
    with TreeEnsembleClassifier
    with TreeEnsembleRegressor
    with Unique
    with Unsqueeze
    with Upsample
    with Where
    with Xor
    with ZipMap
