package org.emergentorder.onnxZIO

import scalaz.zio.Task
import org.emergentorder.onnx._
import org.emergentorder.union.UnionType._
import scala.reflect.ClassTag
import spire.implicits._
import spire.math.UByte
import spire.math.UShort
import spire.math.Complex
import spire.algebra.Field
import spire.math.Numeric
import scala.language.higherKinds

trait SqueezenetZIO {
  val ConvZIO: ConvZIO
  val ReluZIO: ReluZIO
  val MaxPoolZIO: MaxPoolZIO
  val ConcatZIO: ConcatZIO
  val DropoutZIO: DropoutZIO
  val GlobalAveragePoolZIO: GlobalAveragePoolZIO
  val SoftmaxZIO: SoftmaxZIO
  val dataSource: DataSourceZIO
  def program: Task[Tensor[Float]]  = 
    for {
      nodedata_0 <- dataSource.inputDataZIO[Float]
      nodeconv10_b_0 <-  dataSource.getParamsZIO[Float]("conv10_b_0")
      nodeconv10_w_0 <-  dataSource.getParamsZIO[Float]("conv10_w_0")
      nodeconv1_b_0 <-  dataSource.getParamsZIO[Float]("conv1_b_0")
      nodeconv1_w_0 <-  dataSource.getParamsZIO[Float]("conv1_w_0")
      nodefire2_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire2_expand1x1_b_0")
      nodefire2_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire2_expand1x1_w_0")
      nodefire2_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire2_expand3x3_b_0")
      nodefire2_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire2_expand3x3_w_0")
      nodefire2_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire2_squeeze1x1_b_0")
      nodefire2_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire2_squeeze1x1_w_0")
      nodefire3_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire3_expand1x1_b_0")
      nodefire3_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire3_expand1x1_w_0")
      nodefire3_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire3_expand3x3_b_0")
      nodefire3_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire3_expand3x3_w_0")
      nodefire3_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire3_squeeze1x1_b_0")
      nodefire3_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire3_squeeze1x1_w_0")
      nodefire4_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire4_expand1x1_b_0")
      nodefire4_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire4_expand1x1_w_0")
      nodefire4_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire4_expand3x3_b_0")
      nodefire4_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire4_expand3x3_w_0")
      nodefire4_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire4_squeeze1x1_b_0")
      nodefire4_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire4_squeeze1x1_w_0")
      nodefire5_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire5_expand1x1_b_0")
      nodefire5_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire5_expand1x1_w_0")
      nodefire5_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire5_expand3x3_b_0")
      nodefire5_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire5_expand3x3_w_0")
      nodefire5_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire5_squeeze1x1_b_0")
      nodefire5_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire5_squeeze1x1_w_0")
      nodefire6_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire6_expand1x1_b_0")
      nodefire6_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire6_expand1x1_w_0")
      nodefire6_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire6_expand3x3_b_0")
      nodefire6_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire6_expand3x3_w_0")
      nodefire6_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire6_squeeze1x1_b_0")
      nodefire6_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire6_squeeze1x1_w_0")
      nodefire7_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire7_expand1x1_b_0")
      nodefire7_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire7_expand1x1_w_0")
      nodefire7_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire7_expand3x3_b_0")
      nodefire7_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire7_expand3x3_w_0")
      nodefire7_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire7_squeeze1x1_b_0")
      nodefire7_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire7_squeeze1x1_w_0")
      nodefire8_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire8_expand1x1_b_0")
      nodefire8_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire8_expand1x1_w_0")
      nodefire8_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire8_expand3x3_b_0")
      nodefire8_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire8_expand3x3_w_0")
      nodefire8_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire8_squeeze1x1_b_0")
      nodefire8_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire8_squeeze1x1_w_0")
      nodefire9_expand1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire9_expand1x1_b_0")
      nodefire9_expand1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire9_expand1x1_w_0")
      nodefire9_expand3x3_b_0 <-  dataSource.getParamsZIO[Float]("fire9_expand3x3_b_0")
      nodefire9_expand3x3_w_0 <-  dataSource.getParamsZIO[Float]("fire9_expand3x3_w_0")
      nodefire9_squeeze1x1_b_0 <-  dataSource.getParamsZIO[Float]("fire9_squeeze1x1_b_0")
      nodefire9_squeeze1x1_w_0 <-  dataSource.getParamsZIO[Float]("fire9_squeeze1x1_w_0")
      nodeconv1_1 <- ConvZIO.Conv1ZIO("conv1_1" ,strides = Some((Array(2,2))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(3,3))),X = Some(nodedata_0),W = Some(nodeconv1_w_0),B = Some(nodeconv1_b_0))
      nodeconv1_2 <- ReluZIO.Relu6ZIO("conv1_2" ,X = Some(nodeconv1_1))
      nodepool1_1 <- MaxPoolZIO.MaxPool1ZIO("pool1_1" ,strides = Some((Array(2,2))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(3,3))),X = Some(nodeconv1_2))
      nodefire2_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire2_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodepool1_1),W = Some(nodefire2_squeeze1x1_w_0),B = Some(nodefire2_squeeze1x1_b_0))
      nodefire2_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire2_squeeze1x1_2" ,X = Some(nodefire2_squeeze1x1_1))
      nodefire2_expand1x1_1 <- ConvZIO.Conv1ZIO("fire2_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire2_squeeze1x1_2),W = Some(nodefire2_expand1x1_w_0),B = Some(nodefire2_expand1x1_b_0))
      nodefire2_expand1x1_2 <- ReluZIO.Relu6ZIO("fire2_expand1x1_2" ,X = Some(nodefire2_expand1x1_1))
      nodefire2_expand3x3_1 <- ConvZIO.Conv1ZIO("fire2_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire2_squeeze1x1_2),W = Some(nodefire2_expand3x3_w_0),B = Some(nodefire2_expand3x3_b_0))
      nodefire2_expand3x3_2 <- ReluZIO.Relu6ZIO("fire2_expand3x3_2" ,X = Some(nodefire2_expand3x3_1))
      nodefire2_concat_1 <- ConcatZIO.Concat4ZIO("fire2_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire2_expand1x1_2),Some(nodefire2_expand3x3_2)))
      nodefire3_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire3_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire2_concat_1),W = Some(nodefire3_squeeze1x1_w_0),B = Some(nodefire3_squeeze1x1_b_0))
      nodefire3_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire3_squeeze1x1_2" ,X = Some(nodefire3_squeeze1x1_1))
      nodefire3_expand1x1_1 <- ConvZIO.Conv1ZIO("fire3_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire3_squeeze1x1_2),W = Some(nodefire3_expand1x1_w_0),B = Some(nodefire3_expand1x1_b_0))
      nodefire3_expand1x1_2 <- ReluZIO.Relu6ZIO("fire3_expand1x1_2" ,X = Some(nodefire3_expand1x1_1))
      nodefire3_expand3x3_1 <- ConvZIO.Conv1ZIO("fire3_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire3_squeeze1x1_2),W = Some(nodefire3_expand3x3_w_0),B = Some(nodefire3_expand3x3_b_0))
      nodefire3_expand3x3_2 <- ReluZIO.Relu6ZIO("fire3_expand3x3_2" ,X = Some(nodefire3_expand3x3_1))
      nodefire3_concat_1 <- ConcatZIO.Concat4ZIO("fire3_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire3_expand1x1_2),Some(nodefire3_expand3x3_2)))
      nodepool3_1 <- MaxPoolZIO.MaxPool1ZIO("pool3_1" ,strides = Some((Array(2,2))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(3,3))),X = Some(nodefire3_concat_1))
      nodefire4_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire4_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodepool3_1),W = Some(nodefire4_squeeze1x1_w_0),B = Some(nodefire4_squeeze1x1_b_0))
      nodefire4_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire4_squeeze1x1_2" ,X = Some(nodefire4_squeeze1x1_1))
      nodefire4_expand1x1_1 <- ConvZIO.Conv1ZIO("fire4_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire4_squeeze1x1_2),W = Some(nodefire4_expand1x1_w_0),B = Some(nodefire4_expand1x1_b_0))
      nodefire4_expand1x1_2 <- ReluZIO.Relu6ZIO("fire4_expand1x1_2" ,X = Some(nodefire4_expand1x1_1))
      nodefire4_expand3x3_1 <- ConvZIO.Conv1ZIO("fire4_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire4_squeeze1x1_2),W = Some(nodefire4_expand3x3_w_0),B = Some(nodefire4_expand3x3_b_0))
      nodefire4_expand3x3_2 <- ReluZIO.Relu6ZIO("fire4_expand3x3_2" ,X = Some(nodefire4_expand3x3_1))
      nodefire4_concat_1 <- ConcatZIO.Concat4ZIO("fire4_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire4_expand1x1_2),Some(nodefire4_expand3x3_2)))
      nodefire5_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire5_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire4_concat_1),W = Some(nodefire5_squeeze1x1_w_0),B = Some(nodefire5_squeeze1x1_b_0))
      nodefire5_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire5_squeeze1x1_2" ,X = Some(nodefire5_squeeze1x1_1))
      nodefire5_expand1x1_1 <- ConvZIO.Conv1ZIO("fire5_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire5_squeeze1x1_2),W = Some(nodefire5_expand1x1_w_0),B = Some(nodefire5_expand1x1_b_0))
      nodefire5_expand1x1_2 <- ReluZIO.Relu6ZIO("fire5_expand1x1_2" ,X = Some(nodefire5_expand1x1_1))
      nodefire5_expand3x3_1 <- ConvZIO.Conv1ZIO("fire5_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire5_squeeze1x1_2),W = Some(nodefire5_expand3x3_w_0),B = Some(nodefire5_expand3x3_b_0))
      nodefire5_expand3x3_2 <- ReluZIO.Relu6ZIO("fire5_expand3x3_2" ,X = Some(nodefire5_expand3x3_1))
      nodefire5_concat_1 <- ConcatZIO.Concat4ZIO("fire5_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire5_expand1x1_2),Some(nodefire5_expand3x3_2)))
      nodepool5_1 <- MaxPoolZIO.MaxPool1ZIO("pool5_1" ,strides = Some((Array(2,2))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(3,3))),X = Some(nodefire5_concat_1))
      nodefire6_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire6_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodepool5_1),W = Some(nodefire6_squeeze1x1_w_0),B = Some(nodefire6_squeeze1x1_b_0))
      nodefire6_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire6_squeeze1x1_2" ,X = Some(nodefire6_squeeze1x1_1))
      nodefire6_expand1x1_1 <- ConvZIO.Conv1ZIO("fire6_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire6_squeeze1x1_2),W = Some(nodefire6_expand1x1_w_0),B = Some(nodefire6_expand1x1_b_0))
      nodefire6_expand1x1_2 <- ReluZIO.Relu6ZIO("fire6_expand1x1_2" ,X = Some(nodefire6_expand1x1_1))
      nodefire6_expand3x3_1 <- ConvZIO.Conv1ZIO("fire6_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire6_squeeze1x1_2),W = Some(nodefire6_expand3x3_w_0),B = Some(nodefire6_expand3x3_b_0))
      nodefire6_expand3x3_2 <- ReluZIO.Relu6ZIO("fire6_expand3x3_2" ,X = Some(nodefire6_expand3x3_1))
      nodefire6_concat_1 <- ConcatZIO.Concat4ZIO("fire6_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire6_expand1x1_2),Some(nodefire6_expand3x3_2)))
      nodefire7_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire7_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire6_concat_1),W = Some(nodefire7_squeeze1x1_w_0),B = Some(nodefire7_squeeze1x1_b_0))
      nodefire7_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire7_squeeze1x1_2" ,X = Some(nodefire7_squeeze1x1_1))
      nodefire7_expand1x1_1 <- ConvZIO.Conv1ZIO("fire7_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire7_squeeze1x1_2),W = Some(nodefire7_expand1x1_w_0),B = Some(nodefire7_expand1x1_b_0))
      nodefire7_expand1x1_2 <- ReluZIO.Relu6ZIO("fire7_expand1x1_2" ,X = Some(nodefire7_expand1x1_1))
      nodefire7_expand3x3_1 <- ConvZIO.Conv1ZIO("fire7_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire7_squeeze1x1_2),W = Some(nodefire7_expand3x3_w_0),B = Some(nodefire7_expand3x3_b_0))
      nodefire7_expand3x3_2 <- ReluZIO.Relu6ZIO("fire7_expand3x3_2" ,X = Some(nodefire7_expand3x3_1))
      nodefire7_concat_1 <- ConcatZIO.Concat4ZIO("fire7_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire7_expand1x1_2),Some(nodefire7_expand3x3_2)))
      nodefire8_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire8_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire7_concat_1),W = Some(nodefire8_squeeze1x1_w_0),B = Some(nodefire8_squeeze1x1_b_0))
      nodefire8_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire8_squeeze1x1_2" ,X = Some(nodefire8_squeeze1x1_1))
      nodefire8_expand1x1_1 <- ConvZIO.Conv1ZIO("fire8_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire8_squeeze1x1_2),W = Some(nodefire8_expand1x1_w_0),B = Some(nodefire8_expand1x1_b_0))
      nodefire8_expand1x1_2 <- ReluZIO.Relu6ZIO("fire8_expand1x1_2" ,X = Some(nodefire8_expand1x1_1))
      nodefire8_expand3x3_1 <- ConvZIO.Conv1ZIO("fire8_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire8_squeeze1x1_2),W = Some(nodefire8_expand3x3_w_0),B = Some(nodefire8_expand3x3_b_0))
      nodefire8_expand3x3_2 <- ReluZIO.Relu6ZIO("fire8_expand3x3_2" ,X = Some(nodefire8_expand3x3_1))
      nodefire8_concat_1 <- ConcatZIO.Concat4ZIO("fire8_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire8_expand1x1_2),Some(nodefire8_expand3x3_2)))
      nodefire9_squeeze1x1_1 <- ConvZIO.Conv1ZIO("fire9_squeeze1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire8_concat_1),W = Some(nodefire9_squeeze1x1_w_0),B = Some(nodefire9_squeeze1x1_b_0))
      nodefire9_squeeze1x1_2 <- ReluZIO.Relu6ZIO("fire9_squeeze1x1_2" ,X = Some(nodefire9_squeeze1x1_1))
      nodefire9_expand1x1_1 <- ConvZIO.Conv1ZIO("fire9_expand1x1_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire9_squeeze1x1_2),W = Some(nodefire9_expand1x1_w_0),B = Some(nodefire9_expand1x1_b_0))
      nodefire9_expand1x1_2 <- ReluZIO.Relu6ZIO("fire9_expand1x1_2" ,X = Some(nodefire9_expand1x1_1))
      nodefire9_expand3x3_1 <- ConvZIO.Conv1ZIO("fire9_expand3x3_1" ,strides = Some((Array(1,1))),pads = Some((Array(1,1,1,1))),kernel_shape = Some((Array(3,3))),X = Some(nodefire9_squeeze1x1_2),W = Some(nodefire9_expand3x3_w_0),B = Some(nodefire9_expand3x3_b_0))
      nodefire9_expand3x3_2 <- ReluZIO.Relu6ZIO("fire9_expand3x3_2" ,X = Some(nodefire9_expand3x3_1))
      nodefire9_concat_1 <- ConcatZIO.Concat4ZIO("fire9_concat_1" ,axis = Some((1)),inputs = Seq(Some(nodefire9_expand1x1_2),Some(nodefire9_expand3x3_2)))
      nodefire9_concat_2 <- DropoutZIO.Dropout7ZIO("fire9_concat_2" ,data = Some(nodefire9_concat_1))
      nodeconv10_1 <- ConvZIO.Conv1ZIO("conv10_1" ,strides = Some((Array(1,1))),pads = Some((Array(0,0,0,0))),kernel_shape = Some((Array(1,1))),X = Some(nodefire9_concat_2._1),W = Some(nodeconv10_w_0),B = Some(nodeconv10_b_0))
      nodeconv10_2 <- ReluZIO.Relu6ZIO("conv10_2" ,X = Some(nodeconv10_1))
      nodepool10_1 <- GlobalAveragePoolZIO.GlobalAveragePool1ZIO("pool10_1" ,X = Some(nodeconv10_2))
      nodesoftmaxout_1 <- SoftmaxZIO.Softmax1ZIO("softmaxout_1" ,input = Some(nodepool10_1))
    } yield (nodesoftmaxout_1)
}
